on:
  push:
  schedule:
    - cron: '12 7 * * 1/3'

jobs: 
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
    - name: verbose
      run: |
        docker -v
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx create --help
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Build
      run: |
        ls
        cd 1.10.0

        docker buildx build . --platform linux/arm/v7 --load -t betashil/unbound
    - name: Push
      run: |
        docker login --username "${{ secrets.HUB_USER }}" --password "${{ secrets.HUB_PASS }}"
        docker push betashil/unbound
