on:
  push:
    paths-ignore:
      - README.md
  schedule:
    - cron: '12 7 * * 1/7'

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Set Environment Variables
      run: |
        echo "PLATFORM=linux/amd64,linux/arm64,linux/arm/v7" >> $GITHUB_ENV
        echo "DOCKERHUB_SLUG=$(echo ${{ secrets.HUB_USER }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_PASS }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Set credentials for github
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Pull changes from MatthewVance/unbound-docker
      run: |
        git pull
        git remote add mvance https://github.com/MatthewVance/unbound-docker
        git fetch --all
        git merge mvance/master --ff
    - name: Push changes
      uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
      with:
        directory: ./
        repository:  averissimo/unbound-docker
        github_token: ${{ secrets.GH_TOKEN }}
    - name: Custom changes
      run: |
        bash av_custom.bash
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./custom-av
        platforms: ${{ env.PLATFORM }}
        build-args: |
          GRAFANA_VERSION=master
          GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
        push: true
        tags: |
            ${{ env.DOCKERHUB_SLUG }}/unbound:latest
