on:
  push:
  schedule:
    - cron: '12 7 * * 1/3'

jobs: 
  build_docker:
    runs-on: ubuntu-latest
    name: Build/Push Docker
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: repo
    - name: Build
      run: |
        ls
        cd repo/1.10.0
        docker build --pull . -f Dockerfile -t betashil/unbound

        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --driver docker-container
        docker buildx build . --platform linux/arm/v7 --load -t betashil/unbound
    - name: Push
      run: |
        docker login --username "${{ secrets.HUB_USER }}" --password "${{ secrets.HUB_PASS }}"
        docker push betashil/unbound
